2018-04-11 22:12:36,672 ERROR: Exception on /index [GET] [in /Users/kadakia/anaconda3/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/kadakia/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/kadakia/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/kadakia/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/kadakia/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/kadakia/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kadakia/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/kadakia/anaconda3/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/kadakia/flask_app/app/routes.py", line 28, in index
    last_url = url_for('index', page=posts.last)
AttributeError: 'Pagination' object has no attribute 'last'
2018-04-11 22:13:42,487 INFO: RohanApp startup [in /Users/kadakia/flask_app/app/__init__.py:45]
2018-04-11 22:18:51,050 INFO: RohanApp startup [in /Users/kadakia/flask_app/app/__init__.py:45]
2018-04-11 22:18:57,789 ERROR: Exception on /user/rmkadakia [GET] [in /Users/kadakia/anaconda3/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/kadakia/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/kadakia/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/kadakia/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/kadakia/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/kadakia/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kadakia/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/kadakia/anaconda3/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/kadakia/flask_app/app/routes.py", line 42, in user
    next_url = next_url, prev_url = prev_url)
  File "/Users/kadakia/anaconda3/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/Users/kadakia/anaconda3/lib/python3.6/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/Users/kadakia/anaconda3/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/kadakia/anaconda3/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/kadakia/anaconda3/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/kadakia/anaconda3/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/kadakia/flask_app/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/kadakia/flask_app/app/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/kadakia/flask_app/app/templates/user.html", line 23, in block "content"
    {% for post in posts %}
TypeError: 'Pagination' object is not iterable
2018-04-11 22:20:02,886 INFO: RohanApp startup [in /Users/kadakia/flask_app/app/__init__.py:45]
2018-04-11 22:21:17,134 INFO: RohanApp startup [in /Users/kadakia/flask_app/app/__init__.py:45]
2018-04-11 22:28:30,669 INFO: RohanApp startup [in /Users/kadakia/flask_app/app/__init__.py:45]
2018-04-11 22:28:36,301 ERROR: Exception on /user/rmkadakia [GET] [in /Users/kadakia/anaconda3/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/kadakia/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/kadakia/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/kadakia/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/kadakia/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/kadakia/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kadakia/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/kadakia/anaconda3/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/kadakia/flask_app/app/routes.py", line 42, in user
    next_url = next_url, prev_url = prev_url)
  File "/Users/kadakia/anaconda3/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/Users/kadakia/anaconda3/lib/python3.6/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/Users/kadakia/anaconda3/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/kadakia/anaconda3/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/kadakia/anaconda3/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/kadakia/anaconda3/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/kadakia/flask_app/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/kadakia/flask_app/app/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/kadakia/flask_app/app/templates/user.html", line 23, in block "content"
    {% for post in posts %}
TypeError: 'Pagination' object is not iterable
2018-04-11 22:30:39,442 ERROR: Exception on /user/rmkadakia [GET] [in /Users/kadakia/anaconda3/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/kadakia/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/kadakia/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/kadakia/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/kadakia/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/kadakia/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kadakia/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/kadakia/anaconda3/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/kadakia/flask_app/app/routes.py", line 42, in user
    next_url = next_url, prev_url = prev_url)
  File "/Users/kadakia/anaconda3/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/Users/kadakia/anaconda3/lib/python3.6/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/Users/kadakia/anaconda3/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/kadakia/anaconda3/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/kadakia/anaconda3/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/kadakia/anaconda3/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/kadakia/flask_app/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/kadakia/flask_app/app/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/kadakia/flask_app/app/templates/user.html", line 23, in block "content"
    {% for post in posts %}
TypeError: 'Pagination' object is not iterable
